---
title: "R para quem usa o excel"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## registros para um futuro texto para os alunos da Unirio


https://www.r-bloggers.com/tidyquant-v1-0-0-pivot-tables-vlookups-in-r/
https://www.r-bloggers.com/r-for-excel-users-pivot-tables-vlookups-in-r/



I’m pleased to announce the release of tidyquant version 1.0.0 that includes Excel in R (Pivot Tables, VLOOKUPs, Sum-Ifs, and 100+ Excel Functions). I’ve also integrated the FREE Tiingo API via riingo. There are a ton of new features that are covered in my ‘R for Excel Users Tutorial’ on Business Science_.
Highlights: tidyquant 1.0.0



### Citar o post do IBPAD
https://www.ibpad.com.br/blog/analise-de-dados/r-para-usuarios-de-excel/
https://shotwell.ca/posts/r_for_excel_users/

## Recriando o procV no R (Recreating VLOOKUP in R)
https://formalizedcuriosity.net/post/recreating-vlookup-in-r/

## How to Overcome Messy Excel Sheets in R
https://www.sportscidata.com/how-to-rearrange-a-messy-excel-sheet-in-r/

## A Comprehensive Guide to Transitioning from Excel to R by Alyssa Columbus
https://rpubs.com/acolumbus/how-to-use-r-with-excel

## how-to-do-excel-vlookup-in-r-using-left_join-merge/
https://www.r-bloggers.com/how-to-do-excel-vlookup-in-r-using-left_join-merge/


# corrigindo no R os  dados confusos do excel
https://cran.r-project.org/web/packages/tidyxl/vignettes/tidyxl.html
https://rfortherestofus.com/2019/12/how-to-clean-messy-data-in-r/
# cabeça das tabelas
https://nacnudus.github.io/unpivotr/
consertando o excel bagunçado com o R
https://www.sportscidata.com/how-to-rearrange-a-messy-excel-sheet-in-r/
https://www.r-bloggers.com/tidying-messy-excel-data-tidyxl/

https://luisdva.github.io/rstats/unheadr-cat/



3. Common Excel Functions in R
To find more information about how to use each of these R functions, type ?function (e.g. ?sum) in the RStudio Console, and you’ll be provided with comprehensive and clear R documentation. If you need even more information about an R function, type “how to use ___ function in R” or something similar into Google.


3. Common SPSS Functions in R
mostrar as funcoes do R para:
recode in the same variable
recode in diferent variable
compute







